<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dip</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^.*\bfn\s*(\w+\s*)?\([^\)]*\)(\s*\{[^\}]*)?\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>Dipper</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b[A-Z]\b</string>
			<key>name</key>
			<string>storage.type.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\"[\w\s\d\!\@\#]*\"</string>
			<key>name</key>
			<string>string.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(c_[a-z0-9_]+|[a-z_][a-z0-9_]*_t)\b</string>
			<key>name</key>
			<string>storage.type.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A-Z_][A-Z0-9_]+)\b</string>
			<key>name</key>
			<string>constant.other.source.dipper</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'(?=([^\'\\]|\\(x\h{2}|u\{\h{1,6}\}|n|r|t|0|"|'|\\))\')</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.source.dipper</string>
			<key>patterns</key>
			<array>
				<!--
				<dict>
					<key>include</key>
					<string>#dipper_escaped_character</string>
				</dict>
				-->
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.dipper</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.dipper</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(fn)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
			<key>name</key>
			<string>keyword.control.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(import|from)\b</string>
			<key>name</key>
			<string>keyword.other.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(class|struct)\b</string>
			<key>name</key>
			<string>support.class.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|else|for|if|elif|loop|match|return|while|continue)\b</string>
			<key>name</key>
			<string>keyword.control.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(as|in|box|not)\b</string>
			<key>name</key>
			<string>keyword.operator.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(fn|class|struct|macro)\b</string>
			<key>name</key>
			<string>invalid.illegal.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(True|False)\b</string>
			<key>name</key>
			<string>constant.language.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(self)\b</string>
			<key>name</key>
			<string>variable.language.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!::)\b(null|int|float|str|bool|func|list|array|obj)\b</string>
			<key>name</key>
			<string>storage.type.source.dipper</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#!?\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>comment.block.attribute.source.dipper</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dipper_string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dipper_raw_string</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9][0-9_]*(i|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0x[0-9a-fA-F_]*[0-9a-fA-F][0-9a-fA-F_]*(i|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0o[0-7_]*[0-7][0-7_]*(i|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0b[0-1_]*[0-1][0-1_]*(i|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9][0-9_]*((f32|f64)|([eE][+-]?[0-9_]*[0-9][0-9_]*(f32|f64)?)|(\.([0-9][0-9_]*([eE][+-]?[0-9_]*[0-9][0-9_]*)?(f32|f64)?)?))\b</string>
			<key>name</key>
			<string>constant.numeric.float.source.dipper</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#[!/][^/].*</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.documentation.source.dipper</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.hash.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[-=&lt;&gt;&amp;|..|!~@;:?+*/%^'#$]|\b_\b</string>
			<key>name</key>
			<string>keyword.operator.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[(){}\[\]]|::</string>
			<key>name</key>
			<string>meta.default.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(print|del)\b</string>
			<key>name</key>
			<string>support.function.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[a-z_][a-z0-9_]*(?=\()</string>
			<key>name</key>
			<string>support.function.source.dipper</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Copy|Send|Sized|Sync|Drop|Fn|FnMut|FnOnce|Box|ToOwned|Clone|PartialEq|PartialOrd|Eq|Ord|AsRef|AsMut|Into|From|Default|Iterator|Extend|IntoIterator|DoubleEndedIterator|ExactSizeIterator|Option|Some|None|Result|Ok|Err|SliceConcatExt|String|ToString|Vec)\b</string>
			<key>name</key>
			<string>support.type.source.dipper</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>dipper_escaped_character</key>
		<dict>
			<key>match</key>
			<string>\\(x\h{2}|u\{\h{1,6}\}|n|r|t|0|"|'|\\)</string>
			<key>name</key>
			<string>constant.character.escape.source.dipper</string>
		</dict>
		<key>dipper_raw_string</key>
		<dict>
			<key>begin</key>
			<string>r(#*)"</string>
			<key>end</key>
			<string>"(\1)</string>
			<key>name</key>
			<string>string.quoted.double.raw.source.dipper</string>
		</dict>
		<key>dipper_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.source.dipper</string>
			<key>patterns</key>
			<array>
				<!--
				<dict>
					<key>include</key>
					<string>#dipper_escaped_character</string>
				</dict>
				-->
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.dipper</string>
	<key>uuid</key>
	<string>1c3a5f7b-4a11-4af5-1024-09ecaaffffff</string>
</dict>
</plist>
